name: oauth1
version: 1.1.0-alpha
description: OAuth1 clients and servers conforming to "\"RFC 5849: The OAuth 1.0 Protocol\".
homepage: https://github.com/nbspou/dart-oauth1
author: kumar8600 <kumar1@hotmail.co.jp>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  crypto: ^2.0.0
  http: '>=0.11.0 < 0.13.0'

dev_dependencies:
  args: ^1.5.1
  test: ^1.0.0
